#!/usr/bin/env php
<?php

use DI\Container;
use Tools\Index;

// Load composer dependencies.
require_once __DIR__ . '/vendor/autoload.php';

$container = new Container();

$commands = $container->get(Index::class)->get_all_commands();
$command = $argv[1] ?? '';

if (array_key_exists($command, $commands)) {
  $container->get($commands[$command])->route(array_slice($argv, 2));
  exit;
}

echo "Invalid command. Available commands are:\n- " . implode("\n- ", array_keys($commands));
