<?php

$rules = [
    '&gt;:(' => 'angry.gif',
    ':)' => 'smile.gif',
    ':(' => 'frown.gif',
    '8D' => 'awesome.gif',
    ':|' => 'blank.gif',
    'B)' => 'cool.gif',
    '(!)' => 'exclamation.gif',
    ':D' => 'grin.gif',
    ':3' => 'kittyface.gif',
    'O_o' => 'O_o.gif',
    '(?)' => 'question.gif',
    ':o' => 'shocked.gif',
    'X(' => 'sick.gif',
    ':p' => 'tongue.gif',
    ':P' => 'tongue.gif',
    '-_-' => 'unamused.gif',
    ':-.' => 'unsure.gif',
    ':S' => 'wacky.gif',
    'X)' => 'x).gif',
    'x)' => 'x).gif',
    ';)' => 'wink.gif',
    ':wub:' => 'love.gif',
    ':lt:' => 'lt.gif',
    ':gt:' => 'gt.gif',
    'XD' => 'XD.gif',
    '^_^' => '^_^.gif',
    ':cookie:' => 'cookie.gif',
];
