<?php
$rules=Array(
 "8D"=>"awesome.png",
 ":|"=>"blank.png",
 "B)"=>"cool.png",
 ":D"=>"grin.png",
 ":)"=>"happy.png",
 "&lt;3"=>"love.png",
 "&gt;:("=>"mad.png",
 ":O"=>"oh.png",
 ":o"=>"oh.png",
 ":("=>"sad.png",
 "X("=>"sick.png",
 ":/"=>"slant.png",
 ":P"=>"tongue.png",
 ":p"=>"tongue.png"
);
?>
